
import React, { useState } from 'react';
import { 
  DollarSign, 
  ShoppingBag, 
  TrendingUp, 
  Sparkles, 
  Activity,
  AlertCircle
} from 'lucide-react';
import { AuditLogEntry } from '../types';
import { analyzeShiftData } from '../services/geminiService';
import { CURRENCY_SYMBOL } from '../constants';

interface Props {
  stats: { totalRevenue: number; orderCount: number };
  logs: AuditLogEntry[];
}

export const Dashboard: React.FC<Props> = ({ stats, logs }) => {
  const [analysis, setAnalysis] = useState("");
  const [loading, setLoading] = useState(false);

  const avgOrderValue = stats.orderCount > 0 
    ? stats.totalRevenue / stats.orderCount 
    : 0;

  const handleAnalyze = async () => {
    setLoading(true);
    // Prepare logs for the AI (convert to readable strings)
    const logStrings = logs.map(l => 
      `${l.timestamp.toLocaleTimeString()} - ${l.action}: ${l.details || ''}`
    );
    
    const result = await analyzeShiftData(logStrings);
    setAnalysis(result);
    setLoading(false);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500">
      
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-gray-800">Manager Dashboard</h2>
        <p className="text-gray-500">Real-time session insights and performance metrics.</p>
      </div>

      {/* KPI Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Revenue Card */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-start justify-between">
          <div>
            <p className="text-sm font-medium text-gray-500 mb-1">Total Revenue</p>
            <h3 className="text-3xl font-bold text-gray-900">
              {CURRENCY_SYMBOL}{stats.totalRevenue.toFixed(2)}
            </h3>
            <div className="flex items-center gap-1 mt-2 text-emerald-600 text-xs font-medium">
              <TrendingUp size={12} />
              <span>Session Active</span>
            </div>
          </div>
          <div className="p-3 bg-emerald-50 rounded-lg text-emerald-600">
            <DollarSign size={24} />
          </div>
        </div>

        {/* Orders Card */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-start justify-between">
          <div>
            <p className="text-sm font-medium text-gray-500 mb-1">Transactions</p>
            <h3 className="text-3xl font-bold text-gray-900">{stats.orderCount}</h3>
            <p className="text-xs text-gray-400 mt-2">Completed orders</p>
          </div>
          <div className="p-3 bg-blue-50 rounded-lg text-blue-600">
            <ShoppingBag size={24} />
          </div>
        </div>

        {/* Avg Value Card */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm flex items-start justify-between">
          <div>
            <p className="text-sm font-medium text-gray-500 mb-1">Avg. Ticket</p>
            <h3 className="text-3xl font-bold text-gray-900">
              {CURRENCY_SYMBOL}{avgOrderValue.toFixed(2)}
            </h3>
            <p className="text-xs text-gray-400 mt-2">Per transaction</p>
          </div>
          <div className="p-3 bg-purple-50 rounded-lg text-purple-600">
            <Activity size={24} />
          </div>
        </div>
      </div>

      {/* AI Insights Section */}
      <div className="bg-gradient-to-r from-indigo-900 to-indigo-800 rounded-2xl p-8 text-white shadow-xl relative overflow-hidden">
        {/* Background Pattern */}
        <div className="absolute top-0 right-0 -mt-10 -mr-10 w-64 h-64 bg-white opacity-5 rounded-full blur-3xl"></div>
        
        <div className="relative z-10">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 bg-white/10 rounded-lg backdrop-blur-sm">
              <Sparkles className="text-yellow-400" size={20} />
            </div>
            <h3 className="text-xl font-bold">AI Shift Analysis</h3>
          </div>

          <div className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/10 min-h-[120px]">
            {analysis ? (
              <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
                <p className="text-lg leading-relaxed text-indigo-50 font-medium">
                  "{analysis}"
                </p>
                <p className="text-xs text-indigo-300 mt-4 text-right">Generated by Gemini AI</p>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-indigo-200 py-4">
                <Activity className="mb-2 opacity-50" />
                <p>Ready to analyze {logs.length} audit logs for anomalies and trends.</p>
              </div>
            )}
          </div>

          <div className="mt-6 flex justify-end">
            <button 
              onClick={handleAnalyze}
              disabled={loading || logs.length === 0}
              className="bg-white text-indigo-900 px-6 py-3 rounded-lg font-bold shadow-lg hover:bg-indigo-50 active:transform active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {loading ? (
                <>
                  <span className="animate-spin">⟳</span> Analyzing Shift...
                </>
              ) : (
                <>
                  Generate End-of-Day Report
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Recent System Activity */}
      <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex items-center gap-2">
           <AlertCircle size={18} className="text-gray-500" />
           <h3 className="font-bold text-gray-700">Recent System Events</h3>
        </div>
        <div className="divide-y divide-gray-100 max-h-[300px] overflow-y-auto">
          {logs.length === 0 ? (
             <div className="p-6 text-center text-gray-400">No logs available.</div>
          ) : (
             [...logs].reverse().slice(0, 10).map(log => (
               <div key={log.id} className="px-6 py-3 hover:bg-gray-50 flex items-center justify-between transition-colors">
                 <div>
                    <span className="text-sm font-semibold text-gray-800">{log.action}</span>
                    <span className="text-xs text-gray-500 ml-2">{log.details}</span>
                 </div>
                 <span className="text-xs font-mono text-gray-400">
                    {log.timestamp.toLocaleTimeString()}
                 </span>
               </div>
             ))
          )}
        </div>
      </div>
    </div>
  );
};
